### ISSUE TITLE
CSV Reading errors

### ISSUE THREAD

**Issue by Twister42** [EaseTech/easytest#61] opened 2012-11-12 11:01 UTC
Hello,
It seems that csvReader is not always reading the values in the good order.
With this csv : 

```
testInitServices,classname,dateDebut,dateFin
,model.ServiceBean.class,08/12/2012,09/12/2013
,model.ServiceBean.class,10/12/2012,11/12/2013
```

The _String[] splitValues = csvReader.getValues();_ in _CSVDataLoader_ sometimes return a splitValues[] array with shuffled elements.

I did the test with a small snippet and got strange result from the javacsv library : 

``` java
File f = new File("services.csv");
FileReader fr = new FileReader(f);
CsvReader csv = new CsvReader(fr);
while (csv.readRecord()) {
    System.out.println(Arrays.toString(csv.getValues()));
}
```

gives : 

```
[testInitServices, classname, dateDebut, dateFin]
[, 08/12/2012, 09/12/2013, model.ServiceBean.class]
[, 10/12/2012, 11/12/2013, model.ServiceBean.class]
```

or : 

```
[testInitServices, classname, dateDebut, dateFin]
[, model.ServiceBean.class, 08/12/2012, 09/12/2013]
[, model.ServiceBean.class, 10/12/2012, 11/12/2013]
```

After some experimentation it seems the library is very sensitive to file encoding and have some pseudo-random results. My test classes fails exactly 2 of 3 times.

**Comment by anujgandharv** [comment] 2012-11-12 12:23
Thanks Twister42 for pointing out the potential issue with CSVReader. I will now start looking in to the issue with first trying to replicate the issue and then look at how we can fix this. i will keep you posted.

**Comment by Twister42** [comment] 2012-11-12 12:59
Just made another test and it is getting stranger :

``` java
public class TestClass {
    public static void main(String[] args) throws Exception {
        TestClass t = new TestClass();
        CsvReader csv;

        csv = new CsvReader(new FileReader(new File(t.getClass().getClassLoader().getResource("services.csv").toURI())));
        while (csv.readRecord()) {
            System.out.println(Arrays.toString(csv.getValues()));
        }

        csv = new CsvReader(new FileReader(new File("D:\\workspace\\project\\src\\test\\resources\\services.csv")));
        while (csv.readRecord()) {
            System.out.println(Arrays.toString(csv.getValues()));
        }
    }
}
```

Gives :

```
[testInitServices, classname, dateDebut, dateFin]
[, 08/12/2012, 09/12/2013, model.ServiceBean.class]
[, 10/12/2012, 11/12/2013, model.ServiceBean.class]
[testInitServices, classname, dateDebut, dateFin]
[, model.ServiceBean.class, 08/12/2012, 09/12/2013]
[, model.ServiceBean.class, 10/12/2012, 11/12/2013]
```

**Comment by Twister42** [comment] 2012-11-12 13:07
Ok, found... After a clean/build the file in the target directory is mine. 
When I run the test it is getting overridden with a modified file :

```
testInitServices,classname,dateDebut,dateFin
"",09/12/2013,model.ServiceBean.class,08/12/2012
"",11/12/2013,model.ServiceBean.class,10/12/2012
```

Is it EasyTest who is modifying the files ?

**Comment by Twister42** [comment] 2012-11-12 13:18
Ok, got my answer, it is normal, but disturbing.
Modifying the data files means we cannot rerun the tests because the source file has been modified. Moreover the data fields has been reordered and the values do not matches the headers anymore. I think it should be better to write the results in a file with a different name.

**Comment by anujgandharv** [comment] 2012-11-12 13:41
You are right. The issue is with writing the data back to the file. Ideally modifying the data files should not prevent you from reusing the same file again. And thats the idea.

I just found the bug in the writeData functionality of CSV. We are writing the data to the file without matching the data values with their corresponding data headers. I am on it to fix this issue. I am hoping to fix it by EOD today. Will keep you posted.

Regarding writing data to a separate file, we have it as an agenda with us to provide the users of EasyTest with the option of writing the data to the same file or to a separate file. I will keep you posted on the developments on the same.

Cheers!

**Comment by anujgandharv** [comment] 2012-11-12 15:12
Hi Twister42,
This issue is now fixed in the master branch. You can take the latest soource and test with it.
Alternativel, you can wait for a wek or two and this will be available in the 0.6.4 release of easytest.
Let me know if you face any issues.

UPDATE: As a bonus, you can now have standard java objects like Date, Integer, Double etc as part of your method parameter and EasyTest will take care of converting your String into appropriate objects.
Take a look at this example which takes the same set of input test data as you have in the above example and which declares the Date as Date object(either java.util.Date or java.sql.Date will work).
https://github.com/EaseTech/easytest/blob/master/src/test/java/org/easetech/easytest/example/TestConditionsSupportedByDataDrivenTest.java

Look at testBug test case :)

Cheers!

**Comment by Twister42** [comment] 2012-11-12 15:25
Thank you for your reactivity.
I will try your fix asap. 
For the converters : glad to hear it, I already wrote one for the dates but not the other types.

**Comment by anujgandharv** [comment] 2012-11-12 15:31
You are welcome. You now shouldn't have to write the converters for Date etc. Also, we will be extending our support to  auto-convert a lot more complex objects in the coming days.

**Comment by Twister42** [comment] 2012-11-12 15:36
Possibility to build Lists from a CSV would be a great feature. For exemple you could use a converter that convert a whole CSV to a list of objects.

**Comment by anujgandharv** [comment] 2012-11-12 15:49
Yes that's a possibility but I am not able to visualize where a List of Objects would be useful. 
We have plans(exact design is currently under consideration) so that a user can provide the data that he wants to pass as a list(or a Set) in the test data file and then the framework will identify and auto convert the string of data into a list (or a Set etc).

**Comment by Twister42** [comment] 2012-11-12 16:01
I have some sorting/filtering/merging algorithms working with Lists/Sets/Maps to tests, so passing a list is mandatory.
I agree I can test the inner functions of the algorithms to ensure they are working but it would not cover everything. Some tests needs at least 3 objects to cover some cases.
Moreover I do generate speed reports in order to monitor the algorithms performance. To do so I need to be able to feed them with enough data.

**Comment by anujgandharv** [comment] 2012-11-12 16:37
Right. I think I get what you are saying. In short, you want some functionality so that you can get ALL the data sets in one go in a test method.Is it correct?

Would it be possible for you to write up a separate issue mentioning the actual functionality you require along with an example.
That would really help the EasyTest team to visualize, understand and then take a decision whether we could support it or not.
If everything goes well, we could provide you with the functionality in couple of weeks time. :)

Cheers!

**Closed as completed** 2012-11-15 17:06 UTC
